name: Remove old artifacts

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

defaults:
  run:
    shell: bash

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '2 months'
        skip-tags: true
